apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/vendure-docker-compose-default: "true"
        io.kompose.service: worker
    spec:
      containers:
          - name: worker
            command: ["/usr/src/app/wait-for-it.sh"]          
            args: ["database:5432","--", "yarn", "start:worker"]
            env:
              - name: DATABASE_HOST
                value: database
              - name: DATABASE_PORT
                value: "5432"
            image: aditiecomm.azurecr.io/worker
      restartPolicy: Always
