apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cd
  name: changedetect
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  selector:
    io.kompose.service: cd