apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cd
  name: changedetect
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cd
  template:
    metadata:
      labels:
        io.kompose.network/vendure-docker-compose-default: "true"
        io.kompose.service: cd
    spec:
      containers:
        - env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: Tz
              value: "Etc/CET"
          image: europe-west1-docker.pkg.dev/mdidedda/vendure/changedetection
          name: changedetect
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
      restartPolicy: Always