name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: cd Storefront && docker build . --file Dockerfile --tag ${{ secrets.AWS.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS.REGION }}.us-east-1.amazonaws.com/vendure/storefront
    - name: login into ECR
      run: aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${{ secrets.AWS.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS.REGION }}.amazonaws.com
    - name: create remote ECR Repository
      run: aws ecr create-repository --repository-name vendure/server
    - name: Transfer container to ECR
      run: docker push ${{ secrets.AWS.ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS.REGION }}.us-east-1.amazonaws.com/vendure/storefront
