name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
      run: cd Storefront && docker build . --file Dockerfile --tag $ACCOUNT_ID.dkr.ecr.$REGION.us-east-1.amazonaws.com/vendure/storefront
    - name: login into ECR
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
      run: aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
    - name: create remote ECR Repository
      run: aws ecr create-repository --repository-name vendure/server
    - name: Transfer container to ECR
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
      run: docker push $ACCOUNT_ID.dkr.ecr.$REGION.us-east-1.amazonaws.com/vendure/storefront
