name: IAC (Deploy on K8s)

on:
  push:
    branches: [ "master" ]
    paths:
      - k8s-Google/**
      - .github/workflows/build-iac.yml

jobs:

  build:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
    - uses: actions/checkout@v4
    - name: Assume eks_user_role to manage EKS and login to EKS
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.REGION }}
      run:  export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
            $(aws sts assume-role \
            --role-arn arn:aws:iam::$ACCOUNT_ID:role/eks_user_role \
            --role-session-name iac_changes \
            --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
            --output text))
      run: aws eks update-kubeconfig --region $REGION --name eks-badapp
      run: cd k8s-Google && kubectl apply -f .