name: Building database from common Image

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/build-database.yml
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
    - uses: actions/checkout@v4
    - name: login into ECR and upload SQL image
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.REGION }}
      run: |
        export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
            $(aws sts assume-role \
            --role-arn arn:aws:iam::$ACCOUNT_ID:role/ecr_user_role \
            --role-session-name iac_changes \
            --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
            --output text))
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
          aws ecr describe-repositories --repository-names vendure/sql || aws ecr create-repository --repository-name vendure/sql
          docker pull bitnami/postgresql:9.4.6
          docker tag bitnami/postgresql:9.4.6 $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/vendure/sql
          docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/vendure/sql
