name: Building database from common Image

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/build-database.yml
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    environment: AWS
    steps:
    - uses: actions/checkout@v4
    - name: login into ECR and upload SQL image
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.REGION }}
      run: |
        aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
        aws ecr create-repository --repository-name vendure/sql  2>&1 || true
        docker pull bitnami/postgresql
        docker tag bitnami/postgresql $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/vendure/sql
        docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/vendure/sql
