name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Storefront/Dockerfile --tag europe-west1-docker.pkg.dev/mdidedda/vendure/storefront/storefront:latest
